### ISSUE TITLE
svg extra line

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/jsme#10]
In the svg on the right there are 3 extra lines:

![image](https://cloud.githubusercontent.com/assets/1484241/19242135/270c327a-8f12-11e6-94dc-8a9678cd7e7d.png)

![image](https://cloud.githubusercontent.com/assets/1484241/19242147/39add438-8f12-11e6-98f1-b008ee74cacc.png)

**Comment by targos** [comment]
now the svg looks like this:
![image](https://cloud.githubusercontent.com/assets/2352663/19512063/714e95c4-95ea-11e6-9d9f-e91a32808900.png)

**Comment by brunob54** [comment]
Sorry about the bug. It should be fixed now.

**Comment by lpatiny** [comment]
It's working now, thanks!
