### ISSUE TITLE
SVG rendering with OCL not possible for reactions

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/jsme#12]
Currently you should make a fall back in case of reactions because OCL does not allow to render it

**Comment by brunob54** [comment]
In reaction mode, there is no menu entry for SVG export.

**Comment by lpatiny** [comment]
I was thinking about the method 

`window.jsmeApplet.getMolecularAreaGraphicsString();`

That seems to use the new svg systematically without possibility to disable it.

**Comment by brunob54** [comment]
The method getMolecularAreaGraphicsString() has not changed.

**Comment by lpatiny** [comment]
Sorry an error in my testcase
